name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/api-rest
  
  pull_request:
    branches:
      - feature/api-rest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: tic-tac-toe

    - name: Install OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
        unzip dependency-check-10.0.4-release.zip
        # Verifica el nombre exacto del directorio descomprimido
        ls -l  # Esto listará los archivos para que se vea el nombre
        mv dependency-check-* dependency-check  # Se debe de renombrar el directorio


    - name: Grant execute permissions for Dependency-Check
      run: chmod +x dependency-check/bin/dependency-check.sh

    - name: Run OWASP Dependency-Check
      run: |
        ./dependency-check/bin/dependency-check.sh --project "Tic Tac Toe" --scan ./tic-tac-toe/src

    - name: Build Docker image
      run: docker build -t tic-tac-toe tic-tac-toe/.

    - name: Run Docker Container
      run: docker run -d -p 3000:3000 tic-tac-toe
