name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test/preparation
  pull_request:
    branches:
      - main
      - test/preparation
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: tic-tac-toe
      
    - name: Test Cucumber and generate JSON report
      run: npm run cucumber -- --format json:./cucumber-report.json
      working-directory: tic-tac-toe

    - name: Run unit tests
      run: npm test
      working-directory: tic-tac-toe

    - name: Upload Cucumber report
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: tic-tac-toe/cucumber-report.json

    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version  
    - name: Build and run Docker Compose
      run: |
        docker compose up --build -d 
      working-directory: tic-tac-toe

    - name: Install OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
        unzip dependency-check-10.0.4-release.zip
        # Verifica el nombre exacto del directorio descomprimido
        ls -l  # Esto listará los archivos para que se vea el nombre
        mv dependency-check-* dependency-check  # Se debe de renombrar el directorio
    - name: Grant execute permissions for Dependency-Check
      run: chmod +x dependency-check/bin/dependency-check.sh

    - name: Run OWASP Dependency-Check
      run: |
        ./dependency-check/bin/dependency-check.sh --project "Tic Tac Toe" --scan ./tic-tac-toe/src
    - name: Stop and clean Docker Compose
      run: |
        docker compose down  
      working-directory: tic-tac-toe

