name: CI/CD Pipeline

on:
  push:
    branches:
      - api-rest/docker
  
  pull_request:
    branches:
      - api-rest/docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: tic-tac-toe

    - name: Build Docker image
      run: docker build -t tic-tac-toe tic-tac-toe/.


    - name: Run Docker Container
      run: docker run -d -p 3000:3000 tic-tac-toe