name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/console
  pull_request:
    branches:
      - feature/console

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: Semana1/Actividad1/tic-tac-toe

      - name: Run tests
        run: npm test
        working-directory: Semana1/Actividad1/tic-tac-toe

      - name: Build Docker image
        run: docker build -t tic-tac-toe .
        working-directory: Semana1/Actividad1/tic-tac-toe

      - name: Run Docker container
        run: docker run -d -p 3000:3000 tic-tac-toe

      - name: Stop and clean Docker
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker rmi tic-tac-toe || true
